services:
  iris:
    image: intersystemsdc/iris-community:latest-cd-zpm
    environment:
      IRIS_USERNAME: demo
      IRIS_PASSWORD: demo
    restart: always
    hostname: iris
    ports:
      - 1972:1972
      - 52773:52773

  jupyter:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      OPENAI_API_KEY: sk-N84wsFAuOZNbYfq853q6D1XJCibzRfnjYk5txC700vT3BlbkFJRktCqqeKcDyKYvoxr07rEbcZ4D_o9IqkBHZ9ECRm8A
      IRIS_HOSTNAME: iris
    restart: always
    hostname: jupyter
    ports:
      - 8888:8888
